### PR TITLE
Fix from

### LINKED ISSUE #1: from implementation doesn't match documentation
# `from` function

According to the documentation:

```js
# Create a binary UUID from a valid uuid string
const mUUID2 = MUUID.from('393967e0-8de1-11e8-9eb6-529269fb1459')

# Create a binary UUID from a MongoDb Binary
# This is useful to get MUUIDs helpful toString() method
const mUUID3 = MUUID.from(/** MongoDb Binary of SUBTYPE_UUID */)
```

Type *should* therefore be:

```js
from(value: string | Binary) => Binary
``` 

However, it's presently:

```js
from(value: string) => Binary
from(value: Binary) => string
```

# REPL

```js
u = require('uuid-mongodb')
```
```
{ v1: [Function: v1], v4: [Function: v4], from: [Function: from] }
```

```js
u.v1()
```
```
Binary {
  _bsontype: 'Binary',
  sub_type: 4,
  position: 16,
  buffer: <Buffer 95 0d 05 40 7c c9 11 e9 b8 6e 29 57 8a 1f 42 38>,
  toString: [Function: bound ]
}
```

```js
u.from(u.v1())
```
```
'99413910-7cc9-11e9-b86e-29578a1f4238'
```

```js
u.from(u.from(u.v1()))
```
```
Binary {
  _bsontype: 'Binary',
  sub_type: 4,
  position: 16,
  buffer: <Buffer a0 50 79 50 7c c9 11 e9 b8 6e 29 57 8a 1f 42 38>,
  toString: [Function: bound ]
}
```

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Closes #1

**EDIT**: Force pushed away some excess white space I'd introduced - nothing functional.

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
More fixes:

* `from(Binary)` was allowing users to convert 36 byte buffers (UTF8 encoding hex strings)
    * Test added, then subsequently fixed.
* "should throw when converting an Binary non SUBTYPE_UUID" test was incorrect.
    * Test was "succeeding" because it was attempting to store 4 bytes, not because the sub-type was being validated (it wasn't).
    * Subsequently added `sub_type` validation to ensure the test passes i.e. That `from` correctly throws an error when encountering `Binary` that are _not_ `SUBTYPE_UUID` (even if they're 16 bytes in length).

**Comment by Benjamin-Dobell** [comment]
Force pushed corrections for linting issues. Might be worth setting the linter up client side, so contributors can lint before pushing.

The linter had pointed out usage of `Binary()` instead of `new Binary()` in my change-set. Slightly humorous as I'd specifically changed my own usages from `new Binary()` to `Binary()` after the fact in order to match existing usage through-out the `uuid-mongodb_spec.js`. It would seem as though Codacy only report linting issues on lines in the diff.

Anyway, I've just fixed the usages in my diff. However, there are still other usages of `Binary()` instead of `new Binary()` through-out the code-base.

**Comment by Benjamin-Dobell** [comment]
* Force pushed some additional test fixes.

Namely the tests were doing:

```js
assert.throws(Function, string)
```

However, `assert.throw()s` doesn't accept a string as its second parameter. The strings being passed in therefore aren't being used. If they were being used the tests would actually fail because the strings being provided actually _don't_ match message of the `Error`s being thrown. 

`assert.throws()` accepts `object | Regexp | (Error) => boolean` as its 2nd parameter. In Node 10+ also accepts an `Error`, but the tests are running on 8.4 so I've simply opted for replacing the strings with equivalent `Regexp`.

**Comment by cdimascio** [comment]
Thanks a lot @Benjamin-Dobell. Will have a look shortly

**Comment by cdimascio** [comment]
@all-contributors please add @Benjamin-Dobell for code

**Pull request merged**
