### PR TITLE
Updated dependencies (including the mongodb v4.13.x peer dependency).

### PR DESCRIPTION
**Pull request by erichkuba**

### CODE REVIEW

**Comment by erichkuba** [comment]
@cdimascio I don't seem to be able to review the PR and merge. Can you please do so and publish the package _(you may want to bump the version)_.

Our [fork](https://github.com/apigames-core/uuid-mongodb) & [npm package](https://www.npmjs.com/package/@apigames/uuid-mongodb) have been updated accordingly.

**Comment by cdimascio** [comment]
let's consider matching  major versions rather than minor. this will be safe given that minor version updates should be backward compatible

perhaps keep 3 as and match `4`s major version e.g.
```
peerDependencies": {
    "mongodb": "3.6.x || 3.7.x || 4.x"
...

**Comment by erichkuba** [comment]
Yes, I agree. They seem to have accelerated their release cadence, and it's creating quite a bit of work all around. If something breaks, as a result of pinning to the major, we can deal with it. I'll update the PR  in a few minutes' time.

**Review by cdimascio — APPROVED** [review]

**Comment by cdimascio** [comment]
changes in v`2.5.3`

**Pull request merged**
